# Generated by Django 5.0.6 on 2024-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('quantity', models.FloatField()),
                ('quantity_type', models.CharField(choices=[(1, 'Kg'), (2, 'vnt.')], default='1', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
