# Generated by Django 5.1.1 on 2024-09-16 18:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('quantity_type', models.CharField(choices=[('1', 'Added'), ('2', 'Removed'), ('3', 'Moved')], default='1', max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='items.item')),
                ('move_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='move_to', to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
