# Generated by Django 5.1.1 on 2024-09-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_itemsactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsActions',
            new_name='ItemAction',
        ),
    ]
