# Generated by Django 5.1.1 on 2024-09-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_itemaction_created_by_alter_itemaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemaction',
            old_name='quantity_type',
            new_name='action',
        ),
    ]
