# Generated by Django 5.1.1 on 2024-09-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_itemtype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemaction',
            name='from_location',
            field=models.CharField(default='', max_length=128),
        ),
    ]
