# Generated by Django 5.1.1 on 2024-09-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_itemaction_from_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemaction',
            name='reason',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
