# Generated by Django 5.0.6 on 2024-10-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='from_location',
            field=models.CharField(default='', max_length=128, verbose_name='Arrived from'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_name', to='items.itemtype', verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='items.location'),
        ),
        migrations.AlterField(
            model_name='itemaction',
            name='move_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_to', to='items.location'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Serial number'),
        ),
    ]
